### ISSUE TITLE
Webhook hmac invalid with admin app e webhook created inside admin dashboard with latest shopify library following examples.

### ISSUE THREAD

**Issue by trevisan92** [Shopify/shopify-api-js#1038]
# Issue summary
I have create a shopify admin app with an admin access token and a webhook all inside admin dashboard.
I follow the example from the documentation here :  
https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/guides/custom-store-app.md 
https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/guides/webhooks.md

I see other issue with same problem resolved but for me the problem persist.
I try to swap secret key with admin key but this dosen't work.

I'm behind ngrok.
 
```
import express from "express";
import "@shopify/shopify-api/adapters/node";
import { shopifyApi, ApiVersion } from "@shopify/shopify-api";
import { restResources } from "@shopify/shopify-api/rest/admin/2023-10";

const shopify = shopifyApi({
  apiSecretKey: "api secret key",
  apiVersion: ApiVersion.October23,
  isCustomStoreApp: true,
  adminApiAccessToken: "admin access token starts with shpa_",
  isEmbeddedApp: false,
  // hostName: "7690-46-234-194-10.ngrok-free.app",
  hostName: "woshm.myshopify.com",
  restResources,
});

const session = shopify.session.customAppSession("woshm.myshopify.com");

const app = express();

app.post("/webhooks", express.text({ type: "*/*" }), async (req, res) => {
  console.log(req.body);
  try {
    const validation = await shopify.webhooks.validate({
      rawBody: req.body,
      rawRequest: req,
      rawResponse: res,
    });
    console.log(validation); // HMAC INVALIDO
  } catch (error) {
    console.log(error);
  }
});

app.listen(3000);
```

- `@shopify/shopify-api` version: 8.0.2
- Node version: 21 e 16
- Operating system: Linux

```
{ valid: false, reason: 'invalid_hmac' }
```

## Expected behavior

The hmac need to be valid
## Actual behavior
The hmac is invalid

**Comment by paulomarg** [comment]
Hey folks! I'm trying to investigate this problem, and it seems like our validation is currently correct in most cases, but there are some where it fails.

My current suspicion is that there is something in the webhook payload that might be getting encoded in a different way. Could you please tell me whether:
- you're using a language with special character (as in, not English) on your test data?
- whether _not_ using any special characters causes it to work?

Thank you!

**Comment by lakshay-saini-au8** [comment]
{"webhooks":[{"id":14325267,"address":"correct_url","topic":"app\/uninstalled","created_at":"2023-11-30T10:04:52-05:00","updated_at":"2023-11-30T10:04:52-05:00","format":"json","fields":[],"metafield_namespaces":[],"api_version":"2023-07","private_metafield_namespaces":[]}]}

await this.shopify_client.webhooks.process({
        rawBody: req.rawBody,
        rawRequest: req,
        rawResponse: res,
      });

[shopify-api/INFO] Receiving a webhook request
[shopify-api/DEBUG] Webhook request is well formed | {apiVersion: 2023-07, domain: shop_name.myshopify.com, topic: APP_UNINSTALLED, webhookId: eddb6fb78d34}
[shopify-api/DEBUG] Webhook validation failed | {apiVersion: 2023-07, domain: shop_name.myshopify.com, topic: APP_UNINSTALLED, webhookId: eddb6fb78d34}
[shopify-api/DEBUG] Webhook request is invalid, returning 401: Could not validate request HMAC


Hey, @paulomarg  I am to register the webhook.
Also on uninstall, I am getting the webhook request.
Tried all the possible solutions but still getting this possibility to share your thoughts

**Comment by paulomarg** [comment]
Thanks for all the details @StefanAlumier. I think you're doing all of the right things on your app, it just won't work with events triggered from the admin settings because it uses a different key. I went into a little more detail in [this comment](https://github.com/Shopify/shopify-app-template-remix/issues/396#issuecomment-1823144889).

With that being said, the easiest way to fully test a webhook is using either the CLI command or triggering the actual event in your development store (e.g. changing a product's title will trigger the `PRODUCTS_UPDATE` event).

Since the focus of this package is on the app side of things, we currently don't plan on supporting the events configured in an admin's settings (which aren't tied to the app). I have however taken this as feedback and forwarded it to the webhooks team to see if there are any improvements we can make for testing app webhooks.

Hope this helps!
