### ISSUE TITLE
Session.isActive bug on Online Session

### ISSUE THREAD

**Issue by bluedge** [Shopify/shopify-api-js#663]
When using **Online Session** Session.active method fails to validate expired Date properly

- `@shopify/shopify-api` version: 6.1.0
- Node version: 16.18.0
- Operating system: OSX 13.0.1

```
session.isActive(shopify.config.scopes);
// Fails to check a valid expire Date
```

I could fix this in Session Class the following way

The class Currently read:
```
if (scopesUnchanged &&
         this.accessToken &&
         (!this.expires || this.expires >= new Date())) {
         return true;
}
```

This fixes the issue. `this.expires` is converted in a proper JS Date, so it can be compared to `new Date()`
```
if (scopesUnchanged &&
         this.accessToken &&
         (!this.expires || new Date(this.expires) >= new Date())) {
         return true;
}
```

**Comment by bluedge** [comment]
Thanks for your reply @cquemin 
I save the Session object from Shopify Oauth in Redis as a string
`return await this.client.set(sessionId, JSON.stringify(session));`

I retrieved it as a String form Redis and parse it (Expires is a String at this point)
```
const session = await this.client.get(sessionId);
return new Session(JSON.parse(session));
```

In the past weeks, I tried to cast my session.expires as an Date but Shopify Session Class Interface was expecting a String. I see that the last version has change that to a Date now.

Now I could solve this issue by casting expires into a Date - I hope it help someone.
```
const ss = JSON.parse(session);
ss.expires = ss.expires ? new Date(ss.expires) : undefined;
return new Session(ss);
```

IMO, Methods like Session.fromPropertyArray could be private methods of the Session class.
The Session constructor should return a well formatted object, with the expected types for each value.
This would return a consistent Object, Developers could use it consistently in there own DB class implementation.

**Comment by cquemin** [comment]
Oh I understand a bit more.
I don't know if you're aware but we do offer multiple implementations for session storage. In particular [one for redis](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-session-storage-redis). All the session storage implementations takes care of the serialization and deserialization for you. So you would, not face this problem.

However if you prefer to work on your custom version, it is totally possible. In which case I'd suggest to look at the implementation of the redis session storage to have an idea. But the key part that could help solving your issue is that `Session.fromPropertyArray` is the counterpart of the method `session.toPropertyArray`. 

We have decided to export them because this could allow you to serialize and deserialization your `Session` with any protocol(json, protocolbuffer, cbor) in a consistent way. And in this particular case it makes more sense to have the constructor using a proper type so that it enforces the consistency of the object created what is required to create them.

In your case you could save the session this way:
```js
JSON.stringify(session.toPropertyArray())
```
And you could load it this way:
```js
Session.fromPropertyArray(rawResult) // result from redis
```
This way, those methods would ensure types are properly handled and are all "serialisation friendly" without having ypou to worry about.
