### ISSUE TITLE
Webhooks only Http seems to be supported in v6

### ISSUE THREAD

**Issue by jnrepo** [Shopify/shopify-api-js#702]
# Issue summary

Looking at the code [here](https://github.com/Shopify/shopify-api-js/blob/main/lib/webhooks/process.ts#L61), is it not possible to process AWS Eventbridge or Google Pub/sub events? It seems like its deliberate in the code to not process these webhook handlers, but the [docs](https://shopify.dev/apps/webhooks/configuration/eventbridge) say that it is possible to use AWS Eventbridge. What's the workaround? Should I downgrade to v5.3.0?

- `@shopify/shopify-api` version: 6.1.0
- Node version: 16.15.1
- Operating system: MacOS 13.1 Ventura

## Expected behavior

I'm able to use `DeliveryMethod.Eventbridge` type handlers to send webhooks to AWS Eventbridge.

## Actual behavior

I get the log `[shopify-app/ERROR] Failed to process webhook: Error: No HTTP webhooks registered for topic CARTS_UPDATE`

## Steps to reproduce the problem

1. Follow the instructions [here](https://shopify.dev/apps/getting-started/create#step-1-create-a-new-app) and create a new node application.
1. Run `npm run dev` and install the app.
1. In "gdpr.js" file add... 
```
CARTS_UPDATE: {
  deliveryMethod: DeliveryMethod.EventBridge
  arn: "your-arn-address"
}
```
4. Go to your shop. Settings > Notifications and create a webhook for "cart update" and use the ngrok url with `/api/webhooks` as the url.
1. Send a test notification or go to your shop and trigger the event.
1. See error in the log.

**Comment by mkevinosullivan** [comment]
@jnrepo Why are you doing step 4 above (configuring a webhook for `cart/update` in the Admin)?  This is creating a HTTP webhook, which is then being triggered to your app, for which you don't have a handler.

The configuration you've added to `gdpr.js`
```js
CARTS_UPDATE: {
  deliveryMethod: DeliveryMethod.EventBridge
  arn: "your-arn-address"
}
```
... will instruct the library to register the webhook on your behalf ... there is no need to configure it in the Admin.

When the webhook is triggered, it will send the webhook to the `arn` configured.  Only HTTP webhooks will be sent to your app, via `/api/webhooks` path (or whatever path set in the `shopifyApp` configuration).

The reason you're getting the error is because of the HTTP webhook being registered in step 4, which is unnecessary.

**Comment by jnrepo** [comment]
@mkevinosullivan Thanks for the clarification. It wasn't easily apparent through the docs how the AWS Eventbridge webhooks were being registered. Got the webhook setup and working, closing out.
