### ISSUE TITLE
Billing redirect fails on CORS

### ISSUE THREAD

**Issue by tamir-boaideas** [Shopify/shopify-api-js#749]
# Issue summary

Both request and check methods redirect to a confirmation URL, but the frontend encounters a CORS error.

When I tried returning the URL itself and making the redirect from the frontend, I got an error message that said "Host parameter is missing.".

I am still working on a dev store, but I was able to manually navigate to the confirmation URL (paste it in the address bar) without issues.

- `@shopify/shopify-api` version: 6.1.0
- Node version: 18.13.0
- Operating system: MacOS

## Expected behavior

The app should redirect to the confirmation URL.

## Actual behavior

The browser throws a CORS exception.

## Steps to reproduce the problem

1. Create a new shopify/cli node app template.
2. Define 2 different plans in the billingConfig.
3. Try to protect a route using the check method as a middleware
4. Try to switch plans using the request method

**Comment by jksjaz** [comment]
I am facing the same issue even when the app is deployed on a domain. Did you find any solution?

**Comment by Rronz** [comment]
@tamir-boaideas @jksjaz Not sure if this helps in your use case. What I did is I sent the URL to my Polaris like this : 

res.status(302).json({statusCode:302,message:confirmationUrl,error:null});
instead of 
res.redirect(confirmationUrl);


And then on the Front-End Side I did this: 

if(data?.statusCode == 302){
      navigate(data.message)
  }

data being the response of the API 
navigate being  import { useNavigate } from "@shopify/app-bridge-react";


This works in my case since I only want to send the Merchant to the Billing Page so I only apply it to the API routes that I use in Polaris. Hopefully, this helps if you need any further clarifications feel free to @ me
