### ISSUE TITLE
Order API not creating Order

### ISSUE THREAD

**Issue by DanishHameed335** [Shopify/shopify-api-js#995]
I am trying to create order using API front Vue Storefront (I need to create custom checkout page thats why using admin API to create order)

I am using following APIs, 
https://shopify.dev/docs/api/admin-rest/2023-07/resources/order

and using following endpoint with method POST as mentioned in docs
/admin/api/2023-07/orders.json

API returns 200 response, and return orders as well, but when I check, order is not created in database, 

it seems like its not accepting request body at all, even if I send blank request body, behaviour is same, no error, just 200 response code, and all the orders in response

Need help if I am doing anything wrong 

Here is the loom video link

https://www.loom.com/share/02b550a5d7d34119b5518c5291e3e83c?sid=90ea11a6-6e6e-44ea-99f4-d83394a47749

**Comment by lizkenyon** [comment]
Hi there 👋 

It looks like this issue is not directly related to the Shopify Javascript API client. 

Could you please share your issue to the [Shopify Community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev), as this is the best place for this query. 

When posting the in the community forums it is very helpful to include the full request body and response of the API call that you are having issues with.
